CREATE DATABASE IF NOT EXISTS ride_compare;
USE ride_compare;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ride_searches (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NULL,
  pickup VARCHAR(255) NOT NULL,
  destination VARCHAR(255) NOT NULL,
  selected_provider VARCHAR(80) NULL,
  selected_mode VARCHAR(80) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);
